dist: xenial
language: bash
services: docker

env:
  global:
    - IMAGE=drpsychick/docker-texlive-pdflatex
  matrix:
    - ALPINE_VERSION=latest
    - ALPINE_VERSION=alpine-3.9
    - ALPINE_VERSION=alpine-3.8
    - ALPINE_VERSION=alpine-3.7

before_script:
  - docker build -t test --build-arg ALPINE_VERSION=$ALPINE_VERSION .
  - export VERSION=$(docker run --rm -it test pdflatex -version |awk '$1 == "pdfTeX" { print $2; exit }' |awk -F- '{print $3}')
  - eval $(ssh-agent -s)
  - echo "$DEPLOY_PRIVATE_KEY" | ssh-add - && ssh-add -l
  - git config --global user.email "github@drsick.net"
  - git config --global user.name "TAG bot"
  - git remote set-url origin "git@github.com:DrPsychick/docker-texlive-pdflatex.git"

script:
  # test always passes
  - echo "Alpine $ALPINE_VERSION pdfTeX $VERSION"
  - >
    echo "Running tests...";
    docker run test pdflatex -version

after_success:
  - >
    if [ "$TRAVIS_BRANCH" = "develop" -a "$ALPINE_VERSION" = "alpine" ]; then
    curl -H "Content-Type: application/json" --data '{"source_type": "Branch", "source_name": "develop"}'
    -X POST "$DOCKERHUB_TRIGGER";
    fi
  - >
    if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    if [ "$ALPINE_VERSION" = "latest" ]; then
    branch="$VERSION";
    curl -H "Content-Type: application/json" --data '{"source_type": "Branch", "source_name": "master"}'
    -X POST "$DOCKERHUB_TRIGGER";
    else
    branch="$VERSION-${ALPINE_VERSION}";
    fi;
    echo "Branch: $branch";
    git checkout -b $branch;
    git pull origin $branch;
    git merge -X theirs --no-edit --no-commit master;
    sed -i -e "s/ALPINE_VERSION=.*/ALPINE_VERSION=$ALPINE_VERSION/" Dockerfile;
    git diff Dockerfile;
    docker build -t $IMAGE:$branch --build-arg ALPINE_VERSION=$ALPINE_VERSION . || exit 1;
    git commit -a -m "automated build on $branch";
    git push -u origin $branch;
    fi
